version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./src
  db:
    image: mysql:8.0.27
    container_name: fabolous_db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/data
    environment:
      - TZ=Europe/Berlin
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD